#!/usr/bin/env python3
"""
SPU — Emergent Gravity: G_eff(delta)

This script explores how the effective gravitational coupling
emerges in the SPU framework as a function of the dynamical
parameter delta.

Assumptions:
- Gravity is emergent, not fundamental
- The effective Planck scale is generated by the density
  of active fermionic degrees of freedom
- No free phenomenological parameters are introduced

Author: SPU Framework
"""

import numpy as np

# ============================================================================
# 1. Fundamental SPU inputs (fixed by theory)
# ============================================================================

# Nominal fermionic capacity (topological)
Nf_nominal = 128.0

# Dynamical delta range (from consistency bounds)
delta_min = 0.50
delta_max = 0.70
num_points = 100

# High-energy emergence scale (GUT scale)
M_GUT = 1.8e16  # GeV

# ============================================================================
# 2. Effective degrees of freedom
# ============================================================================

def Nf_effective(delta):
    """
    Effective number of fermionic degrees of freedom.
    """
    return Nf_nominal - delta


# ============================================================================
# 3. Emergent Planck scale
# ============================================================================

def M_planck_eff(Nf_eff):
    """
    Emergent Planck mass in SPU.

    Assumption:
    M_Pl^2 ~ Nf_eff * M_GUT^2

    This reflects collective gravitational mediation
    by active fermionic modes.
    """
    return np.sqrt(Nf_eff) * M_GUT


# ============================================================================
# 4. Effective Newton constant
# ============================================================================

def G_eff(Mpl):
    """
    Effective Newton constant:
    G = 1 / M_Pl^2   (natural units)
    """
    return 1.0 / (Mpl ** 2)


# ============================================================================
# 5. Scan over delta
# ============================================================================

deltas = np.linspace(delta_min, delta_max, num_points)

print("=" * 70)
print("SPU — Emergent Gravity Scan")
print("=" * 70)
print("delta     Nf_eff     M_Pl_eff [GeV]        G_eff [GeV^-2]")
print("-" * 70)

for d in deltas:
    Nf_eff = Nf_effective(d)
    Mpl = M_planck_eff(Nf_eff)
    G = G_eff(Mpl)

    print(f"{d:5.3f}   {Nf_eff:8.3f}   {Mpl:14.4e}   {G:14.4e}")

print("=" * 70)
print("Scan completed.")
print("Gravity emerges dynamically from Nf_eff(delta).")
